name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            # Configure Firewall
            ufw allow 80/tcp
            ufw allow 443/tcp
            ufw allow 22/tcp
            ufw --force enable
            
            # Deploy Application
            cd TelTelDownload
            git pull origin main
            echo "ADMIN_USERNAME=${{ secrets.ADMIN_USERNAME }}" > .env
            echo "ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }}" >> .env
            docker-compose up -d --build
